### ISSUE TITLE
「編輯區在上」版型測試： Outlook在條列文章部份會跑版，live mail部份正常（軟體版本live mail 2012 16.4.3.3528.0331）、部份開信會有問題（讀取即live mail即當掉整個程式關閉、或只顯示到第二區塊的第一則，軟體版本live mail 2011 15.4.3.3555.0308）。測試gmail，無法一次完整顯示整封信（只顯示到第二區塊的第一則），需另開網頁。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#13]

**Comment by YawenLin** [comment]
前項跑版已解決。

待解決：gmail無法完整顯示。
A.在瀏覽器版：無法一次完整顯示整封信（只會顯示到第四個「閱讀文章」按鈕），需另開網頁。（會顯示「[未顯示完整郵件內容]  查看整封郵件」）
B.在APP：無法一次完整顯示整封信（只會顯示到第四個「閱讀文章」按鈕），即使點選「檢視整封郵件」後，顯示的內容無法向右拖曳，仍無法看到全部電子報內容。
