### ISSUE TITLE
原“維護人”欄若已有資料，再加選會不正確，需修正。（加選維護人清單選擇時，原資料和第一筆勾選的資料會不見，新勾選的第二筆以上維護人的才會被存檔）

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#40]
範例：
已有維謢人Ａ、Ｂ，再加選Ｃ，存檔後，維謢人為空值；
已有維謢人Ａ、Ｂ，再加選Ｃ和Ｄ，存檔後，維謢人只剩Ｄ。

**Comment by YawenLin** [comment]
1."維護人"欄無法取消勾選本次以前的已勾選項目
2.補述之前已回報的：「加選維護人清單選擇時，原資料和第一筆勾選的資料會不見，新勾選的第二筆以上維護人的才會被存檔」←因為新勾選的資料會跟原資料被合併成一筆，形成一個不在存的資料，可能因此所以才會消失

**Comment by booksyi** [comment]
更新為不保留原資料，每次都是全部重選  
  
已於 TNET_Patch 2019080601.zip 更新

**Comment by YawenLin** [comment]
選擇的作者"姓名"欄空白時,存檔會錯誤
![2019-08-06_19h08_56](https://user-images.githubusercontent.com/43978622/62535332-b7779100-b87d-11e9-83bb-987207c24fcc.jpg)

**Comment by booksyi** [comment]
已於 TNET_Patch 2019081901.zip 更新

**Comment by YawenLin** [comment]
OK
