### ISSUE TITLE
「圖片排序」為空白時，後台可以存檔，但前台讀文章時會發生錯誤，請在後台強制把「排序」存為數字，或限制要為數字後才能存檔。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#42]

**Comment by booksyi** [comment]
已於 TNET_Patch 2018110901.zip 更新

**Comment by YawenLin** [comment]
還是有點問題。
若有人在後台編輯時刪除了"排序"裡的數字，或key了國英文，欄位值會是空值，前台讀取時會發生錯誤。
希望後台可以增加檢查，存檔時"排序"欄非數值時，不可存檔。

**Comment by booksyi** [comment]
已於 TNET_Patch 2019011001.zip 更新

**Comment by YawenLin** [comment]
OK
