### ISSUE TITLE
建立關鍵字可由現有關鍵字列表點選。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#47]

**Comment by booksyi** [comment]
之前已有實作該功能  
但點進去會因為要顯示大量的關鍵字所以畫面卡住  
不知道是不是這個原因造成你們的環境無法正常運作  
這次修改成點進去預設顯示搜尋的結果  
等到頁面上的列表建好後，左上方的顯示全部按鈕才可以點選  
  
已於 TNET_Patch 2019072301.zip 更新

**Comment by YawenLin** [comment]
測試OK
