### ISSUE TITLE
Banner 點擊數就沒有資料紀錄。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#51]

**Comment by YawenLin** [comment]
一、關聯有兩個地方

1. 路徑：Analyze
　統計> 分析報表

2. 路徑：BannerStatistics
統計> BANNER點閱數

二、因為BANNER點閱數的＂版位＂下項選項仍是BANNER舊版位的名字，需改為新版位名字。
![2019-01-19_10h26_28](https://user-images.githubusercontent.com/43978622/51421191-867f8980-1bd5-11e9-8f2f-08cfeea825f0.jpg)
![2019-01-19_10h31_44](https://user-images.githubusercontent.com/43978622/51421192-87b0b680-1bd5-11e9-97aa-607188ea8b0c.jpg)

**Comment by booksyi** [comment]
已於 TNET_Patch 2019072301.zip 更新

**Comment by YawenLin** [comment]
1.目前只會計入Banner點擊目的地是Banner內文的點擊。Banner點擊目的地"超連結"的點擊數未被紀錄，需補上紀錄功能

2.路徑：Analyze　統計> 分析報表
查詢對象為"全站"時，需增加包含「未登入者」的點擊

**Comment by booksyi** [comment]
1 已於 TNET_Patch 2019080701.zip 更新  
2 感覺情境會不合理  
因為這個報表有前後百分比  
未登入者為不同人不應該算在一起跟會員排名比較

**Comment by YawenLin** [comment]
1. OK

2. 包含未登入者給是video和banner這兩個的統計分析用的。然後抱歉之前我也有點弄混了，沒說明清楚。video和banner要顯示的就不是會員百分比（不是要看誰點了它們），而是要知道熱門或冷門的video和banner的標題，所以要把未登入者的點擊也計入，同時也要分割成第二個表格，只有兩或三欄，欄名分別是　合計、前Ｎ%，後Ｙ％。
例如，banner總共被點了100次，前20%的是A廣告(15)、B廣告(1)，前1%的C廣告(1)、D廣告(1)

**Comment by booksyi** [comment]
感覺這個需求比較像 Banner 點擊紀錄的功能    
所以不修改分析報表  
  
另外加入 Video 點擊紀錄的功能  
需要到管理功能權限及選單加入功能代碼「VideoStatistics」  
  
已於 TNET_Patch 2019082201.zip 更新

**Comment by booksyi** [comment]
不修改分析報表的原因  
  
在一個頁面沒有統一的邏輯會造成這個功能的複雜度  
對開發者的後續維護難度會提升許多  
對使用者會難理解該功能的作用而導致實用性降低

**Comment by YawenLin** [comment]
OK
本來的用意是要快速呈現站台使用情形（因為點擊紀錄比較流水帳式）
但也同意你說的複雜度
