### ISSUE TITLE
圓餅圖和長條圖都只會顯示六個顏色，需修正。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#56]
![image](https://user-images.githubusercontent.com/32214837/46595946-49ebbe80-cb0d-11e8-8c00-c427d5bdf991.png)

**Comment by booksyi** [comment]
依照原本的6個顏色循環3次  
每次會變得稍微深一點  
共顯示18個顏色  
  
已於 TNET_Patch 2019081902.zip 更新

**Comment by YawenLin** [comment]
OK
