### ISSUE TITLE
前台影像庫有”日期”，但後台缺少影像庫的「日期」欄，請協助增加此欄，以修改前台顯示排序。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#58]

**Comment by booksyi** [comment]
列為需求變更，不優先處理
編輯欄位是否需要可以在編輯頁面修改?

**Comment by YawenLin** [comment]
需要

**Comment by booksyi** [comment]
列表增加顯示「新增日期」與「排序」欄位  
編輯時「新增日期」無法修改，「排序」可以修改  
前台的影片庫及後台影片管理列表排序都改為先依「日期」再依「排序」  
  
已於 TNET_Patch 2019072301.zip 更新

**Comment by YawenLin** [comment]
1.因目的是要修改不同日放的影片順序（例如補放去年的影片，雖然現在在張貼，但已有今年的影片，故不想顯示在最新，要往以前放），故需可以修改日期才能達到作用。
2."排序"欄測試有誤，無法作用（同一日期影片，修改排序，仍不會變更順序）

**Comment by YawenLin** [comment]
→或者直接將前台及後台改為依"排序"呈現順序(直接忽略日期)
數字大的在上(新)，數字小的在下(舊)

**Comment by booksyi** [comment]
更新為只依照"排序"數字來排序  
但因系統其他功能一律都是數字小的在上，所以影像庫也是小的在上  
如果需要每次新增都放到最上面可以用負數累加 (-1, -2, -3, ...)  
  
已於 TNET_Patch 2019080601.zip 更新

**Comment by YawenLin** [comment]
負值很怪，但測試ＯＫ
