### ISSUE TITLE
電子報的＂最新消息＂文章選擇列表顯示的內容不正確（只有跑幾篇出來而已）

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#62]

**Comment by booksyi** [comment]
從前台程式查已經沒有用到文章狀態的「首頁最新消息」  
故將後台文章列表及編輯頁面的這個狀態移除  
電子報選擇最新消息文章的列表改成與前台一致 (從文章分類找)  
  
已於 TNET_Patch 2019072401.zip 更新

**Comment by YawenLin** [comment]
電子報編輯時雖可選擇文章分類，但顯示結果仍只限定了主分類為"最新消息"的文章，因電子報的"最新消息"是一個版位的名字，不是限定文章分類，故請協助拿掉搜尋結果的文章分類限制。

**Comment by booksyi** [comment]
經討論後直接移除只能選最新消息的限制  
已於 TNET_Patch 2019080201.zip 更新

**Comment by YawenLin** [comment]
可以選了，但有一個使用問題：若最新消息原本已有選定，未先＂清除＂就執行＂文章選擇＂再重選擇另一則，存檔後，會變成空白（未選擇文章）。

**Comment by booksyi** [comment]
已於 TNET_Patch 2019080601.zip 更新

**Comment by YawenLin** [comment]
測試OK
