### ISSUE TITLE
留言板的附件檔案，顯雖然設定的檔案名稱，但下載時沒有依照設定檔名，需修正。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#65]
![image](https://user-images.githubusercontent.com/32214837/46595574-98985900-cb0b-11e8-8070-29f30d6dc3f0.png)
![image](https://user-images.githubusercontent.com/32214837/46595579-9e8e3a00-cb0b-11e8-8803-f765edc70644.png)

**Comment by booksyi** [comment]
已於 TNET_Patch 2018110901.zip 更新

**Comment by YawenLin** [comment]
檔名OK,但缺少副檔名

**Comment by booksyi** [comment]
已於 TNET_Patch 2018110902.zip 更新

**Comment by YawenLin** [comment]
還是沒有副檔案 @@

**Comment by YawenLin** [comment]
OK
