### ISSUE TITLE
前台文章分頁按鈕調整，會自動往下顯示更多頁數。達上限頁數時不再顯示下一頁按鈕。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#66]

**Comment by booksyi** [comment]
之前已調整過，再測試沒有發現問題

**Comment by YawenLin** [comment]
![2018-10-12_17h30_02](https://user-images.githubusercontent.com/43978622/46861171-99e7bf80-ce44-11e8-8c49-61cde6deaeef.jpg)
是指像此畫面的第7頁是最後一頁,按右邊那兩個鈕只是停著不動,但其實看不出來是最後一頁

**Comment by booksyi** [comment]
好

**Comment by booksyi** [comment]
已於 TNET_Patch 2018110901.zip 更新

**Comment by YawenLin** [comment]
OK
