### ISSUE TITLE
退訂電子報原因為統計結果在哪呢？

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#69]

**Comment by booksyi** [comment]
會在後台新增一個該功能的頁面

**Comment by booksyi** [comment]
在電子報訂閱管理的新增連結右邊加入可以連結到退訂原因列表頁面的連結
已於 TNET_Patch 2019071601.zip 更新

**Comment by YawenLin** [comment]
1.如何修改退訂原因選項文字?
2.因為是修改會員資料頁～聯絡人二和聯絡人三若沒有填寫電子信箱，請(1)不要顯示 或 (2)不能修改電子報訂閱狀態
3.因為主要用途是放電子報做取消訂閱申請，但若用直接連結到＂～/Member/Edit＂，會因未登入而被導至首頁，登入後便停留在首頁。能如何解決呢？

**Comment by YawenLin** [comment]
請增加匯出excel功能。

**Comment by booksyi** [comment]
已於 TNET_Patch 2019080501.zip 更新

**Comment by YawenLin** [comment]
1.匯出測試OK
2.不曉得哪個選單代碼才是正確的
(1)因選單裡有一個新增的"EpaperUnsubscriptionStatistics"，但點入會顯示錯誤(如下)
'/' 應用程式中發生伺服器錯誤。
執行階段錯誤
描述: 處理您的要求時發生例外狀況。此外，執行第一個例外狀況的自訂錯誤頁面時發生另一個例外狀況。要求已終止。 

(2)選單也無法再新增"EpaperSubscription"，會顯示錯誤(如下)，回上頁後，會再顯示：代碼重複
錯誤。
處理您的要求時發生錯誤。

**Comment by booksyi** [comment]
因為之前預留的頁面是獨立功能才會有 EpaperUnsubscriptionStatistics  
現在是做在每頁面的連結裡所以沒辦法添加到選單

**Comment by YawenLin** [comment]
OK，那我就刪除EpaperUnsubscriptionStatistics
