### ISSUE TITLE
一個會員帳號會有三個email，三個email的電子報是分開設定訂與退訂。目前的退訂流程設計在修改會員資料，修改會員資料只會顯示第一個聯絡email，如何判斷該會員帳號退訂的是哪一個信箱？

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#70]
尚未修改→(1)先隱藏電子報中的退訂功能選項。(2)先隱藏修改會員資料中的訂閱電子報功能。

**Comment by booksyi** [comment]
編輯個人資料頁面的排版有調整，可以分別設定聯絡人一、二、三的資料與電子報訂閱狀態
已於 TNET_Patch 2019071601.zip 更新

**Comment by YawenLin** [comment]
1.如何修改退訂原因選項文字?
2.因為是修改會員資料頁～聯絡人二和聯絡人三若沒有填寫電子信箱，請(1)不要顯示 或 (2)不能修改電子報訂閱狀態
3.因為主要用途是放電子報做取消訂閱申請，現在功能是做在修改會員資料頁，但電子報的取消訂閱連結是直接連結到＂～/Member/Edit＂，會因未登入而被導至首頁，登入後便停留在首頁，不會回到會員資料修改頁。能如何解決呢？

**Comment by booksyi** [comment]
修改退訂原因選項文字:  
從後台的站台參數設定可以修改

**Comment by booksyi** [comment]
2. 改為不顯示  
3. 現在登入後會導到會員資料修改頁  
已於 TNET_Patch 2019080201.zip 更新

**Comment by YawenLin** [comment]
測試OK
