### ISSUE TITLE
“紡織刊物”於後台文章分類設定的”書名管理”設定「會員模式顯示」為「否」，前台仍在線上，請修正。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#72]
![image](https://user-images.githubusercontent.com/32214837/46602051-b2449b00-cb21-11e8-9a09-ab743b3fba58.png)
![image](https://user-images.githubusercontent.com/32214837/46602056-b5d82200-cb21-11e8-9ec5-d258b97338b0.png)
![image](https://user-images.githubusercontent.com/32214837/46602063-b8d31280-cb21-11e8-8e90-a3ba036a98d0.png)

**Comment by booksyi** [comment]
已於 TNET_Patch 2018101101.zip 更新

**Comment by YawenLin** [comment]
OK
