### ISSUE TITLE
垂直整合鏈次分類，右側欄缺少「熱門文章」單元。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#73]
![image](https://user-images.githubusercontent.com/32214837/46602117-d99b6800-cb21-11e8-8d65-1872b2ef19f0.png)

**Comment by booksyi** [comment]
確認後發現熱門文章是針對點進去的次類別搜尋
原程式沒有對垂直產業鏈搜尋熱門文章的功能故列為需求變更
不優先處理

**Comment by YawenLin** [comment]
好

**Comment by booksyi** [comment]
已於 TNET_Patch 2019082201.zip 更新

**Comment by YawenLin** [comment]
OK
