### ISSUE TITLE
GA程式碼

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#74]
因查看改版後的報表，與去年同期相較，瀏覽量大幅下滑（約只剩1/10，90%差異），
但到訪人次、不重覆瀏覽數量卻是差不多（10%以內差異），
另外，平均網頁停留時間也很不正常的成長（1,000%）。

請問google analytics程式碼放在的位置，跟以前有什麼的差異？
（後台計數器相當於瀏覽量，與去年同期相較也是差不多10%以內差異）
![2018-10-15_16h07_48](https://user-images.githubusercontent.com/43978622/46937671-7ca93000-d094-11e8-8199-3c373f2321fa.jpg)

**Comment by booksyi** [comment]
舊的系統程式是把GA的js檔放到每個頁面的每個版型上
新的系統只有放在套用每個頁面最外層的版型

**Comment by YawenLin** [comment]
因為站內的計數器數值（WebSiteStatistics/List），還是跟改版前的瀏覽量相當。請問站內計數器是放在哪個位置呢？

**Comment by booksyi** [comment]
計數器是放在程式底層，每次瀏覽如果是新的 Session ID 就會+1 (用來避免同一人瀏覽累計)  
從正式機情況及資料面判斷為客戶端使用網路爬蟲瀏覽站台資料  
才會使計數器數值與GA統計數值有大幅的落差  
討論結果為不修改
