### ISSUE TITLE
會員管理

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#76]
1.後台：修改"分頁"數量，或"刪除"後，重新顯示時，需停留在原本的資料位置。（現在會跳到第一頁第一筆）
![2018-10-19_09h42_55](https://user-images.githubusercontent.com/43978622/47193165-1702bf80-d384-11e8-9596-b23d68f2f6a9.jpg)

2.經由前台申請的"免費會員"請預設「前台顯示名稱」為"姓名"。（申請"付費會員"與後台建檔不變，維持"公司名稱"）
![2018-10-19_09h30_14](https://user-images.githubusercontent.com/43978622/47193140-eae73e80-d383-11e8-8bcf-57207e16ef34.jpg)

**Comment by booksyi** [comment]
1. 有更新刪除資料會停留在原頁碼，但切換分頁筆數依然保持跳回第一頁 (之前討論過所以不修改)  
2. 已更新  
  
已於 TNET_Patch 2019080501.zip 更新

**Comment by YawenLin** [comment]
OK
