### ISSUE TITLE
辭典

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#78]
1.後台(/Dictionary)：
(1)搜尋有錯誤訊息
![2018-10-23_16h18_45](https://user-images.githubusercontent.com/43978622/47346538-fc13b080-d6df-11e8-8632-ee5aa6506763.jpg)

(2)換頁有錯誤訊息
![2018-10-23_16h19_23](https://user-images.githubusercontent.com/43978622/47346521-f5853900-d6df-11e8-953e-f539feb58e67.jpg)

錯誤訊息
![2018-10-23_16h17_41](https://user-images.githubusercontent.com/43978622/47346555-03d35500-d6e0-11e8-80ed-6523be44127b.jpg)

2.前台(/Contrast)：顯示搜尋結果時，需維持所設定的搜尋條件設定（"模糊"與"精確"），避免使用者誤解搜尋結果之使用條件
![2018-10-23_16h16_42](https://user-images.githubusercontent.com/43978622/47352227-12276e00-d6ec-11e8-9071-15a5afddf240.jpg)
![2018-10-23_16h17_03](https://user-images.githubusercontent.com/43978622/47352240-15baf500-d6ec-11e8-8310-7c4822b0bb93.jpg)

**Comment by booksyi** [comment]
已於 TNET_Patch 2019011001.zip 更新

**Comment by YawenLin** [comment]
OK
