### ISSUE TITLE
FB的分享內容只有網站IP，缺少網址及標題（文章分享也是一樣），FB分享請加上「民調主題 — Tnet產業民調」及該篇的網址。

### ISSUE THREAD

**Issue by booksyi** [booksyi/Tnet#8]

**Comment by YawenLin** [comment]
目前測試分享功能是可以自動抓到網址及標題，
使用 https://developers.facebook.com/tools/debug/ 工具偵測，
是未設定meta property，包含og:image, og:url, og:type, og:title, og:description, fb:app_id等。

因為在fb分享會抓不到文章的封面圖，僅有變形的logo圖，故目前我先在_Layout.cshtml放了統一先抓logo（因為不知該如何指定到封面圖），同時開啟文章（Detail、Journal、Single）的FB和Line的icon。再請協助後續修改。

**Comment by booksyi** [comment]
文章頁面已於 TNET_Patch 2019032702.zip 更新
若沒有問題再修改民調頁面

**Comment by YawenLin** [comment]
疑似因為加的property不是在<head>裡,所以跑不出來

**Comment by booksyi** [comment]
已於 TNET_Patch 2019081902.zip 更新

**Comment by YawenLin** [comment]
FB分享OK!
(應該不含LINE?因為LINE icon還沒出現,就沒有測)

**Comment by booksyi** [comment]
Line分享問題在 #7
