### ISSUE TITLE
文章回應

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#80]
**一、文章回應通知**
1.當文章有留言時，系統所發的通知信
要寄給：**管理者**（條件：忘記是不是勾選  管理者管理(/Manage)  的"留言板通知"）＋**所有作者**（條件：**啟用中**＋**未勾選  會員管理(/MemberManage)  的"作者不收到回應文章的通知"**）
![2018-10-25_16h45_03](https://user-images.githubusercontent.com/43978622/47487624-5c882680-d875-11e8-9f3d-575e307bbce4.jpg)

今日發現系統寄送有問題（而且似乎沒有共通性）：
我的管理者和作者帳號都沒收到
有勾選"作者不收到回應文章的通知"的作者有收到
管理者沒有收到

（改版前是正常的，今日發現才有問題，也許改版時設定有動到）

**二、文章回應管理**
1.寄發通知　文章留言被管理者已回應寄通知信留言者　條件
需增加判斷條件，　**「是否顯示」為「是」**　才需寄送哦
![2018-10-25_16h54_15](https://user-images.githubusercontent.com/43978622/47488279-a4f41400-d876-11e8-8a47-b1c8bbd09e9f.jpg)

2.文章留言被管理者已回應，寄通知信留言者
通知信的寄件者角色只有一個"T"，需修改為：Tnet全球紡織資訊網
![2018-10-25_16h47_43](https://user-images.githubusercontent.com/43978622/47487840-ce607000-d875-11e8-98f6-1c6b05180ad2.jpg)

**Comment by booksyi** [comment]
寄件人名稱併入 #21   
其他已於 TNET_Patch 2019011001.zip 更新

**Comment by YawenLin** [comment]
仍有問題

一、文章回應通知
1.當文章有留言時，**管理者**和**沒有勾選「作者不收到回應文章的通知」的作者**需收到系統所發的通知信，但目前不會寄送

二、會員管理
1."作者不收到回應文章的通知"的勾選或取消勾選**無法被存檔**
![2019-01-11_10h26_25](https://user-images.githubusercontent.com/43978622/51009610-c1f1d680-158b-11e9-9ebc-7baca47caac6.jpg)

三、文章回應管理
1.當　文章留言被管理者回應時，「是否顯示」為 **「否」** 時，**不用**寄送通知信給留言者哦（因為這種情況可能是　有垃圾留言，要關閉前台顯示）
![2019-01-11_10h33_34](https://user-images.githubusercontent.com/43978622/51009758-6542eb80-158c-11e9-8a35-7c50016bf5c7.jpg)

**Comment by YawenLin** [comment]
粗體字為更新描述

一、文章回應通知
1.當文章有留言時，管理者和沒有勾選「作者不收到回應文章的通知」的作者需收到系統所發的通知信，但目前不會寄送　→ **沒有勾選「作者不收到回應文章的通知」的作者已會收到通知**

二、會員管理
1."作者不收到回應文章的通知"的勾選或取消勾選無法被存檔　→ **測試發現，選其他會員類型可以存檔，只有會員類別是"作者"時無法正確存檔(bug)**

三、文章回應管理
1.當　文章留言被管理者回應時，「是否顯示」為 「否」 時，不用寄送通知信給留言者哦（因為這種情況可能是　有垃圾留言，要關閉前台顯示）

**Comment by booksyi** [comment]
第二點測不出來，還需要更多的資訊或提供給我帳號測試
第三點已修正
第四點是在後台的 web.config 設定
已於 TNET_Patch 2019071601.zip 更新

**Comment by YawenLin** [comment]
第一點：OK
第二點：仍一樣，可用帳號測試（如帳號：test1234）
第三點：OK
第四點：OK

**Comment by booksyi** [comment]
已於 TNET_Patch 2019080201.zip 更新

**Comment by YawenLin** [comment]
測試OK
