### ISSUE TITLE
自動下架的熱門文章

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#82]
1.	首頁的熱門文章裡會顯示已自動下架的文章，需修正。

測試案例：文章「107年度紡織所製程技術開發部技術分享研討會--9/13(四)」設定9/13自動下架，而9/13文章已下架，但仍被首頁的熱門文章收錄。

**Comment by YawenLin** [comment]
首頁的熱門文章下架當日無法更新，當日點選將出現錯誤
![2018-12-14_11h11_06](https://user-images.githubusercontent.com/43978622/49981011-f83e3500-ff90-11e8-982c-6459adbc3e63.jpg)

**Comment by booksyi** [comment]
修改自動下架文章的排程會清除前台熱門文章的暫存資料  
已於 TNET_Patch 2019080201.zip 更新

**Comment by YawenLin** [comment]
測試OK
