### ISSUE TITLE
排程的錯誤訊息

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#86]
**12/1，內容有出現port 8081，目前應沒有使用**

2018-12-01 00:00:01,253 ERROR [DefaultQuartzScheduler_Worker-8] TnetSchedule.Program.Catch - 
                    Message: 發生一或多項錯誤。
                    ToString: System.AggregateException: 發生一或多項錯誤。 ---> System.Net.Http.HttpRequestException: 傳送要求時發生錯誤。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 172.16.7.30:8081
   於 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   於 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   於 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   於 TnetSchedule.Services.RecordMemberService.Execute() 於 D:\Work\TNET\TnetSchedule\TnetSchedule\Services\RecordMemberService.cs: 行 86
   於 TnetSchedule.QuartzJobs.RecordMemberJob.ExecuteJob(IJobExecutionContext context) 於 D:\Work\TNET\TnetSchedule\TnetSchedule\QuartzJobs\RecordMemberJob.cs: 行 20
   於 TnetSchedule.QuartzJobs._QuartzJobBase.<>c__DisplayClass5_0.<Execute>b__1() 於 D:\Work\TNET\TnetSchedule\TnetSchedule\QuartzJobs\_QuartzJobBase.cs: 行 26
   於 TnetSchedule.Program.Catch(Action action) 於 D:\Work\TNET\TnetSchedule\TnetSchedule\Program.cs: 行 135
---> (內部例外狀況 #0) System.Net.Http.HttpRequestException: 傳送要求時發生錯誤。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 172.16.7.30:8081
   於 System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   於 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   於 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 內部例外狀況堆疊追蹤的結尾 ---<---

**Comment by YawenLin** [comment]
電子報寄送失敗時會有的訊息，再請確認是否正常

ToString: System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.IO.IOException: 無法從傳輸連接讀取資料: net_io_connectionclosed。
於 System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(Byte[] buffer, Int32 offset, Int32 read, Boolean readLine)
於 System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine)
於 System.Net.Mail.ReadLinesCommand.Send(SmtpConnection conn)
於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
於 System.Net.Mail.SmtpClient.GetConnection()
於 System.Net.Mail.SmtpClient.Send(MailMessage message)
 --- 內部例外狀況堆疊追蹤的結尾 ---
於 System.Net.Mail.SmtpClient.Send(MailMessage message)
於 TnetSchedule.Helper._SendMail(String to, String title, String body, Boolean isHtml, IEnumerable`1 attachments) 於 D:\Work\TNET\TnetSchedule\TnetSchedule\Helper.cs: 行 233

**Comment by booksyi** [comment]
這個要確認 App.config 裡面 appSettings 底下的設定

**Comment by booksyi** [comment]
有確認正式機上面排程的設定沒有問題
應該是在特定時間站台沒有回應導致錯誤，目前已正常

**Comment by YawenLin** [comment]
下月初再觀察看看

**Comment by YawenLin** [comment]
本月OK
