### ISSUE TITLE
進階搜尋

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#87]
**1.全文搜尋**
需要搜尋到「影像庫」，請修正

**2.進階搜尋**
類別選項：缺少「紡織刊物」及「免費會員專區」
![2018-12-10_10h22_10](https://user-images.githubusercontent.com/43978622/49707280-95cdf780-fc65-11e8-8098-df514decab1c.jpg)

**Comment by YawenLin** [comment]
1.「影像庫」無法被搜尋到。還是「影像庫」沒有辦法出現在列表頁的結果上嗎？

2.進階搜尋「紡織刊物」及「免費會員專區」測試OK

**Comment by booksyi** [comment]
影像庫的資料表跟文章的資料表是不同的，所以類別也不在文章的類別裡
在有輸入標題且沒有選擇分類的情況，標題與日期欄是會搜尋影像庫的

**Comment by YawenLin** [comment]
對，測試進階搜尋是可以搜到。
1.不過用"全文檢索"欄搜尋不到，再請協助納入影像庫的資料表到全文檢索。
2."影像庫"在進階搜尋可以當作是一種"主分類"放進搜尋條件的下拉選單嗎?

**Comment by booksyi** [comment]
已於 TNET_Patch 2019032701.zip 更新

**Comment by YawenLin** [comment]
測試OK
