### ISSUE TITLE
分析報表

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#90]
路徑Analyze
統計> 分析報表

查詢對象：全站
當設定的佔比＂末端＂有數個相同點擊、下載數的會員時，列表頁和明細頁的顯示會員名單需相同（目前會不相同）

例如：設定條件前２０％，末端符合條作的是點擊２次。而點擊２次的會員總共用Ａ～Ｆ等６名，即使會超過２０％的數量，Ａ～Ｆ等６名皆應於列表頁和明細頁的顯示。
（目前情況：列表頁可能顯示了Ａ、Ｂ；明細頁則顯示了Ｃ、Ｄ；而Ｅ、Ｆ則可能都不會顯示）

**Comment by YawenLin** [comment]
1.列表頁：測試OK

2.明細頁：沒有改到

3.同時輸入前後的百分比測試結果：
(1)可以同時顯示前後百分比，但兩者的結果會合併在同一格子裡→應分開；
(2)同時顯示前後百分比時，後百分比的結果沒有明細頁（單獨時則有）。。

**Comment by booksyi** [comment]
已於 TNET_Patch 2019032701.zip 更新

**Comment by YawenLin** [comment]
今天修改的部份OK, 但抱歉我昨天測的不夠仔細:
1.匯出excel部份: 同時輸入前後百分比，只有前百分比會被匯出.
2.百分比計算基礎需修改: 現在是以查詢範圍的人(會員)的數量去計算,但其實是想用計算項目(如"登入次數"、"點閱篇數"等)去做百分比佔比計算. ^^"

**Comment by booksyi** [comment]
已於 TNET_Patch 2019072401.zip 更新

**Comment by YawenLin** [comment]
1."前+後百分比"同時時查詢時,"前 10% 免費會員"欄沒有資料
2."後百分比"的查詢結果不正確（會比符合設定條件的正確資料顯示更多）
3.由查詢結果點進的"明細表"內容值不正確 （和上層查詢用了不同的查詢計算方式，請參照 27 Mar第2點的百分比計算基礎需修改：修改成數量的百分比，不是人數的百分比）
4.匯出的excel,有的欄位會有亂碼（可能因為超出一格的資料長度?）
![2019-07-30_18h00_16](https://user-images.githubusercontent.com/43978622/62120367-08bed800-b2f4-11e9-9ce2-c75a50ac411b.jpg)

**Comment by booksyi** [comment]
第 4 點確實可能是字太多導致  
已修正後百分比邏輯正常使用下  
應該不會需要這麼多字的資料  
故第 4 點不修正  
  
已於 TNET_Patch 2019080501.zip 更新

**Comment by YawenLin** [comment]
某些情況"前 X % 免費會員"仍會不顯示

百分比設定結果有時會不正確，因有個資問題，將用email今天測試的30%結果比對excel檔，紅色和紅底標示處為與設定百分比值差異處。

**Comment by booksyi** [comment]
已於 TNET_Patch 2019080701.zip 更新

**Comment by YawenLin** [comment]
結果仍不正確哦
我用8/6查詢,設定前後30%的結果,比對全部(100%)不相符,
相關資料我用mail給你參考

**Comment by booksyi** [comment]
已於 TNET_Patch 2019082601.zip 更新

**Comment by YawenLin** [comment]
OK
