### ISSUE TITLE
前台最新消息及免費會員專區的URL欄位功能不能連結

### ISSUE THREAD

**Issue by YawenLin** [booksyi/Tnet#93]
/Article/List/1
填URL的文章會進到內頁，需修改為開啟URL

**Comment by YawenLin** [comment]
除＂/Article/List/1＂之外，免費會員專區（於後台＂文章共用管理＂將文章勾選「免登入閱讀全文」或「免費會員專區」）也有相同問題

**Comment by booksyi** [comment]
已於 TNET_Patch 2019071601.zip 更新

**Comment by YawenLin** [comment]
兩者變成不能開連結

網址/Error?aspxerrorpath=/Article/Detail/15980
找不到網頁 
找不到您所要求的內容，或者您沒有檢視該內容的權限。

![2019-07-24_10h57_46](https://user-images.githubusercontent.com/43978622/61761721-25de3d00-ae02-11e9-8205-4016bb073cc3.jpg)

**Comment by YawenLin** [comment]
還是不會開連結，會進內頁

**Comment by booksyi** [comment]
已於 TNET_Patch 2019072401.zip 更新

**Comment by YawenLin** [comment]
測試OK
